### PR TITLE
Use process_view and check for csrf_exempt views

### LINKED ISSUE #11: request.POST is accessed in `CSRFCryptMiddleware`
The [Django docs](https://docs.djangoproject.com/en/1.7/topics/http/middleware/#process-view) say that accessing `request.POST` (or `request.REQUEST`) in middleware should _usually_ be avoided, since it prevents views running after the middleware from being able to modify the upload handlers for the request.

The one exception appears to be Django's own `CsrfViewMiddleware`, since `csrf_exempt()` and `csrf_protect()` let you have explicit control.

One approach in `django-debreach` might be to move from implementing `process_request(...)` to `process_view(self, request, view, ...)` and -- like Django's own CSRF middleware does -- to explicitly test the `view.csrf_exempt` flag and bail out if it's `True`.

Thanks for the useful library!

### PR DESCRIPTION
**Pull request by davepeck**
Fixes #11

### CODE REVIEW

**Comment by davepeck** [comment]
Uh, looks like I somehow borked tying this directly to #11. Sorry about that.

**Comment by lpomfrey** [comment]
Thanks, could you fix the tests as well and add the commit to this PR.

**Comment by davepeck** [comment]
Updated. Testing that the middleware does something meaningful when a view is `csrf_exempt` is a little awkward; suggestions welcome.

**Comment by lpomfrey** [comment]
That test looks fine. The only thing is the second argument should just be the view function (test_view) as opposed to the HttpResponse generated by test_view(request)

**Comment by davepeck** [comment]
Whoops, good catch. One moment.

**Comment by lpomfrey** [comment]
Looks good to me, thanks for the PR.

**Pull request merged**
